import javax.swing.*;
public class details {
    public static void main(String[] args) {
        JFrame frame = new JFrame("Admission Details");
        JLabel label = new JLabel(" Student Personal Details");
        JLabel label2 = new JLabel("Name");
        JTextField fname = new JTextField ("Full Name");
        JTextField mField = new JTextField ("Middle Name");
        JTextField lField = new JTextField ("last Name");
        JLabel label3 = new JLabel ("Date of Birth");
        JTextField blank = new JTextField (" ");
        JLabel label4 = new JLabel ("Email");
        JTextField email = new JTextField (" ");
        JLabel label5 = new JLabel ("Citizenship number");
        JTextField bb = new JTextField (" ");
        JLabel label6 = new JLabel ("Citizenship Issuing Office");  
        JTextField ban = new JTextField (" ");
        JLabel label7 = new JLabel ("Citizenship Issue Date");
        JTextField bb2 = new JTextField (" ");
        JLabel a = new JLabel ("Student Academic Details");
        JLabel b = new JLabel ("Intermediate");
        JLabel c = new JLabel ("College Name");
        JTextField a1 = new JTextField (" ");
        JLabel d = new JLabel ("University Name");
        JTextField a2 = new JTextField (" ");
        JLabel e = new JLabel ("CGPA");
        JTextField a3 = new JTextField (" ");
        JLabel f = new JLabel ("SEE/0-Level");
        JLabel g = new JLabel ("School Name");
        JTextField a4 = new JTextField (" ");
        JLabel h = new JLabel ("University Name");
        JTextField a5 = new JTextField (" ");
        JLabel i = new JLabel ("CGPA Name");
        JTextField a6 = new JTextField (" ");
        JLabel j = new JLabel ("Parents Details");
        JLabel k = new JLabel ("Father");
        JLabel m = new JLabel ("Name");
        JTextField a7 = new JTextField ("Full Name");
        JTextField a8 = new JTextField ("Middle Name");
        JTextField a9 = new JTextField ("last Name");
        JLabel n = new JLabel ("Phone number");
        JTextField c1 = new JTextField (" ");
        JLabel o = new JLabel ("Email");
        JTextField c2 = new JTextField (" ");
        JLabel p = new JLabel ("Citizenship number");
        JTextField c3 = new JTextField (" ");
        JLabel q = new JLabel ("Mother");
        JLabel w = new JLabel ("Name");
        JTextField c4 = new JTextField ("Full Name");
        JTextField c5 = new JTextField ("Middle Name");
        JTextField c6 = new JTextField ("last Name");
        JLabel m1 = new JLabel ("Phone number");
        JTextField c7 = new JTextField (" ");
        JLabel m2 = new JLabel ("Email");
        JTextField c8 = new JTextField (" ");
        JLabel m3 = new JLabel ("Citizenship number");
        JTextField c9 = new JTextField (" ");
        JButton free = new JButton ("Submit");


        label.setBounds(300,20 , 300, 25);
        label2.setBounds(20, 50, 50, 25);
        fname.setBounds(100, 50, 200, 25);
        mField.setBounds(350, 50, 200, 25);
        lField.setBounds(600, 50, 200, 25);
        label3.setBounds(20, 100, 300, 25);
        blank.setBounds(100, 100, 200, 25);
        label4.setBounds(20, 150, 50, 25);
        email.setBounds(100, 150, 250, 25);
        label5.setBounds(20, 200, 300, 25);
        bb.setBounds(150, 200, 250, 25);
        label6.setBounds(20, 250, 300, 25);
        ban.setBounds(180, 250, 250, 25);
        label7.setBounds(20, 300, 300, 25);
        bb2.setBounds(180, 300, 250, 25);
        a.setBounds(200, 350, 300, 25);
        b.setBounds(100, 380, 250, 25);
        c.setBounds(20, 420, 250, 25);
        a1.setBounds(120, 420, 250, 25);
        d.setBounds(20, 460, 250, 25);
        a2.setBounds(120, 460, 250, 25);
        e.setBounds(20, 500, 250, 25);
        a3.setBounds(120, 500, 250, 25);
        f.setBounds(100,540 , 250, 25);
        g.setBounds(20, 580, 250, 25);
        a4.setBounds(120, 580, 250, 25);
        h.setBounds(20, 620, 250, 25);
        a5.setBounds(120, 620, 250, 25);
        i.setBounds(20, 660, 250, 25);
        a6.setBounds(120, 660, 250, 25);
        j.setBounds(900, 150, 250, 25);
        k.setBounds(700, 200, 250, 25);
        m.setBounds(700, 240, 250, 25);
        a7.setBounds(740, 240, 150, 25);
        a8.setBounds(950, 240, 150, 25);
        a9.setBounds(1160, 240, 150, 25);
        n.setBounds(700, 290, 250, 25);
        c1.setBounds(800, 290, 250, 25);
        o.setBounds(700,340 , 250, 25);
        c2.setBounds(740, 340, 250, 25);
        p.setBounds(700, 390, 250, 25);
        c3.setBounds(820, 390, 250, 25);
        q.setBounds(700, 440, 250, 25);
        w.setBounds(700, 490, 250, 25);
        c4.setBounds(740, 490, 150, 25);
        c5.setBounds(950, 490, 150, 25);
        c6.setBounds(1160, 490, 150, 25);
        m1.setBounds(700, 540, 250, 25);
        c8.setBounds(800, 540, 250, 25);
        m3.setBounds(700, 590, 250, 25);
        c9.setBounds(820, 590, 250, 25);
        free.setBounds(700, 700, 250, 25);
        frame.add(label);
        frame.add(label2);
        frame.add(fname);
        frame.add(mField);
        frame.add(lField);
        frame.add(label3);
        frame.add(blank);
        frame.add(label4);
        frame.add(email);
        frame.add(label5);
        frame.add(bb);
        frame.add(label6);
        frame.add(ban);
        frame.add(label7);
        frame.add(bb2);
        frame.add(a);
        frame.add(b);
        frame.add(c);
        frame.add(a1);
        frame.add(d);
        frame.add(a2);
        frame.add(e);
        frame.add(a3);
        frame.add(f);
        frame.add(g);
        frame.add(a4);
        frame.add(h);
        frame.add(a5);
        frame.add(i);
        frame.add(a6);
        frame.add(j);
        frame.add(k);
        frame.add(m);
        frame.add(a7);
        frame.add(a8);
        frame.add(a9);
        frame.add(n);
        frame.add(c1);
        frame.add(o);
        frame.add(c2);
        frame.add(p);
        frame.add(c3);
        frame.add(q);
        frame.add(w);
        frame.add(c4);
        frame.add(c5);
        frame.add(c6);
        frame.add(m1);
        frame.add(c7);
        frame.add(m2);
        frame.add(c8);
        frame.add(m3);
        frame.add(c9);
        frame.add(free);
        frame.setSize(2000,2000);
        frame.setLayout(null);
        frame.setVisible(true);
    }
}
